"""Per-country configuration for profile fields, formats, and available sources."""

COUNTRY_CONFIGS: dict[str, dict] = {
    "US": {
        "name": "United States",
        "flag": "🇺🇸",
        "date_format": "MM/DD/YYYY",
        "currency": "USD",
        "salary_period": "annual",
        "address_labels": {"state": "State", "zip": "ZIP Code"},
        "work_auth_options": [
            "US Citizen",
            "Green Card (Permanent Resident)",
            "H1B Visa",
            "OPT/CPT",
            "EAD",
            "TN Visa",
            "L1 Visa",
            "Other",
        ],
        "show_notice_period": False,
        "show_nationality": False,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+1",
        "default_sources": ["linkedin", "indeed", "ziprecruiter"],
        "default_language": "en",
    },
    "GB": {
        "name": "United Kingdom",
        "flag": "🇬🇧",
        "date_format": "DD/MM/YYYY",
        "currency": "GBP",
        "salary_period": "annual",
        "address_labels": {"state": "County", "zip": "Postcode"},
        "work_auth_options": [
            "UK Citizen",
            "Settled Status (ILR)",
            "Pre-Settled Status",
            "Tier 2 (Skilled Worker) Visa",
            "Graduate Visa",
            "Spousal Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+44",
        "default_sources": ["linkedin", "indeed", "reed", "ziprecruiter"],
        "default_language": "en",
    },
    "DE": {
        "name": "Germany",
        "flag": "🇩🇪",
        "date_format": "DD.MM.YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "Bundesland", "zip": "PLZ"},
        "work_auth_options": [
            "EU/EEA Citizen",
            "German Citizen",
            "Blue Card",
            "Work Permit",
            "Job Seeker Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+49",
        "default_sources": ["linkedin", "indeed", "stepstone"],
        "default_language": "de",
    },
    "IN": {
        "name": "India",
        "flag": "🇮🇳",
        "date_format": "DD/MM/YYYY",
        "currency": "INR",
        "salary_period": "annual",
        "address_labels": {"state": "State", "zip": "PIN Code"},
        "work_auth_options": [
            "Indian Citizen",
            "OCI Cardholder",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": True,
        "phone_prefix": "+91",
        "default_sources": ["linkedin", "indeed", "naukri"],
        "default_language": "hi",
    },
    "AU": {
        "name": "Australia",
        "flag": "🇦🇺",
        "date_format": "DD/MM/YYYY",
        "currency": "AUD",
        "salary_period": "annual",
        "address_labels": {"state": "State/Territory", "zip": "Postcode"},
        "work_auth_options": [
            "Australian Citizen",
            "Permanent Resident",
            "Subclass 482 (TSS) Visa",
            "Subclass 485 (Graduate) Visa",
            "Working Holiday Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": False,
        "show_cover_letter": True,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+61",
        "default_sources": ["linkedin", "indeed", "seek"],
        "default_language": "en",
    },
    "CA": {
        "name": "Canada",
        "flag": "🇨🇦",
        "date_format": "DD/MM/YYYY",
        "currency": "CAD",
        "salary_period": "annual",
        "address_labels": {"state": "Province/Territory", "zip": "Postal Code"},
        "work_auth_options": [
            "Canadian Citizen",
            "Permanent Resident",
            "Open Work Permit",
            "PGWP (Post-Graduation)",
            "LMIA-Based Work Permit",
            "Other",
        ],
        "show_notice_period": False,
        "show_nationality": False,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+1",
        "default_sources": ["linkedin", "indeed", "ziprecruiter"],
        "default_language": "en",
    },
    "AE": {
        "name": "United Arab Emirates",
        "flag": "🇦🇪",
        "date_format": "DD/MM/YYYY",
        "currency": "AED",
        "salary_period": "monthly",
        "address_labels": {"state": "Emirate", "zip": ""},
        "work_auth_options": [
            "UAE National",
            "Resident Visa",
            "Employment Visa",
            "Golden Visa",
            "Visit Visa (Requires Sponsorship)",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+971",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "ar",
    },
    "NZ": {
        "name": "New Zealand",
        "flag": "🇳🇿",
        "date_format": "DD/MM/YYYY",
        "currency": "NZD",
        "salary_period": "annual",
        "address_labels": {"state": "Region", "zip": "Postcode"},
        "work_auth_options": [
            "NZ Citizen",
            "Permanent Resident",
            "Work Visa",
            "Working Holiday Visa",
            "Post-Study Work Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": False,
        "show_cover_letter": True,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+64",
        "default_sources": ["linkedin", "indeed", "seek"],
        "default_language": "en",
    },
    "SG": {
        "name": "Singapore",
        "flag": "🇸🇬",
        "date_format": "DD/MM/YYYY",
        "currency": "SGD",
        "salary_period": "monthly",
        "address_labels": {"state": "", "zip": "Postal Code"},
        "work_auth_options": [
            "Singapore Citizen",
            "Permanent Resident",
            "Employment Pass",
            "S Pass",
            "Work Permit",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+65",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "en",
    },
    "FR": {
        "name": "France",
        "flag": "🇫🇷",
        "date_format": "DD/MM/YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "Région", "zip": "Code Postal"},
        "work_auth_options": [
            "EU/EEA Citizen",
            "French Citizen",
            "Titre de Séjour (Residence Permit)",
            "Passeport Talent",
            "Work Permit",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+33",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "fr",
    },
    "NL": {
        "name": "Netherlands",
        "flag": "🇳🇱",
        "date_format": "DD-MM-YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "Province", "zip": "Postcode"},
        "work_auth_options": [
            "EU/EEA Citizen",
            "Dutch Citizen",
            "Highly Skilled Migrant Visa",
            "Search Year Visa",
            "Work Permit (TWV)",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+31",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "nl",
    },
    "IE": {
        "name": "Ireland",
        "flag": "🇮🇪",
        "date_format": "DD/MM/YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "County", "zip": "Eircode"},
        "work_auth_options": [
            "Irish/EU Citizen",
            "Stamp 4 (Permanent)",
            "Critical Skills Employment Permit",
            "General Employment Permit",
            "Stamp 1G (Graduate)",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": False,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": False,
        "phone_prefix": "+353",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "en",
    },
    "JP": {
        "name": "Japan",
        "flag": "🇯🇵",
        "date_format": "YYYY/MM/DD",
        "currency": "JPY",
        "salary_period": "annual",
        "address_labels": {"state": "Prefecture", "zip": "Postal Code"},
        "work_auth_options": [
            "Japanese Citizen",
            "Permanent Resident",
            "Engineer/Specialist in Humanities Visa",
            "Highly Skilled Professional Visa",
            "Specified Skilled Worker",
            "Working Holiday Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+81",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "ja",
    },
    "CN": {
        "name": "China",
        "flag": "🇨🇳",
        "date_format": "YYYY-MM-DD",
        "currency": "CNY",
        "salary_period": "monthly",
        "address_labels": {"state": "Province", "zip": "Postal Code"},
        "work_auth_options": [
            "Chinese Citizen",
            "Work Permit (Category A)",
            "Work Permit (Category B)",
            "Work Permit (Category C)",
            "Residence Permit",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+86",
        "default_sources": ["linkedin"],
        "default_language": "en",
    },
    "KR": {
        "name": "South Korea",
        "flag": "🇰🇷",
        "date_format": "YYYY.MM.DD",
        "currency": "KRW",
        "salary_period": "annual",
        "address_labels": {"state": "Province/City", "zip": "Postal Code"},
        "work_auth_options": [
            "Korean Citizen",
            "E-7 (Special Occupation) Visa",
            "F-2 (Resident) Visa",
            "F-5 (Permanent Resident) Visa",
            "F-6 (Marriage) Visa",
            "D-10 (Job Seeking) Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+82",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "ko",
    },
    "BR": {
        "name": "Brazil",
        "flag": "🇧🇷",
        "date_format": "DD/MM/YYYY",
        "currency": "BRL",
        "salary_period": "monthly",
        "address_labels": {"state": "State", "zip": "CEP"},
        "work_auth_options": [
            "Brazilian Citizen",
            "Permanent Resident (CRNM)",
            "Work Visa (VITEM V)",
            "Digital Nomad Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": False,
        "show_date_of_birth": True,
        "phone_prefix": "+55",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "pt",
    },
    "ES": {
        "name": "Spain",
        "flag": "🇪🇸",
        "date_format": "DD/MM/YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "Province", "zip": "Postal Code"},
        "work_auth_options": [
            "EU/EEA Citizen",
            "Spanish Citizen",
            "Residence and Work Permit",
            "Highly Qualified Professional Visa",
            "Digital Nomad Visa",
            "Student Visa (with work rights)",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+34",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "es",
    },
    "IT": {
        "name": "Italy",
        "flag": "🇮🇹",
        "date_format": "DD/MM/YYYY",
        "currency": "EUR",
        "salary_period": "annual",
        "address_labels": {"state": "Province", "zip": "CAP"},
        "work_auth_options": [
            "Italian/EU Citizen",
            "Permesso di Soggiorno (Residence Permit)",
            "Blue Card EU",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": True,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+39",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "it",
    },
    "MX": {
        "name": "Mexico",
        "flag": "🇲🇽",
        "date_format": "DD/MM/YYYY",
        "currency": "MXN",
        "salary_period": "monthly",
        "address_labels": {"state": "State", "zip": "Código Postal"},
        "work_auth_options": [
            "Mexican Citizen",
            "Temporary Resident (with work permit)",
            "Permanent Resident",
            "NAFTA/USMCA Professional Visa",
            "Other",
        ],
        "show_notice_period": True,
        "show_nationality": True,
        "show_cover_letter": False,
        "show_photo": True,
        "show_date_of_birth": True,
        "phone_prefix": "+52",
        "default_sources": ["linkedin", "indeed"],
        "default_language": "es",
    },
}

SUPPORTED_COUNTRIES = list(COUNTRY_CONFIGS.keys())

NOTICE_PERIOD_OPTIONS = [
    "Immediate",
    "15 days",
    "30 days",
    "1 month",
    "2 months",
    "3 months",
    "Other",
]


def get_country_config(country_code: str) -> dict:
    """Get config for a country code, falling back to US defaults."""
    return COUNTRY_CONFIGS.get(country_code, COUNTRY_CONFIGS["US"])
